<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{9c66033f-e740-42dd-984e-1f5de6971388}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Traffic : FB_TrafficLight;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Traffic();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="14" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>